image: node:10
stages:
  - build
cache:
  paths:
    - node_modules/
before_script:
  - npm install --registry=https://registry.npm.taobao.org
  - npm install cnpm -g --registry=https://registry.npm.taobao.org
job:
    stage: build
    only:
        - master
    script:
        - npm run lint
        - npm run test
        - npm run build
        - git config --global user.email "landl_ww@163.com"
        - git config --global user.name "landluck"
        - git checkout master
        - node ./publish.js $CNPM_UN $CNPM_PW $CNPM_EM $CNPM_R $GIT_USER_NAME $GIT_USER_PWD